# Generated by Django 5.0.2 on 2024-03-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkout',
            field=models.BooleanField(default=True),
        ),
    ]
